name: Go
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        go-version:
          - 1.16.x
          - 1.17.x
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: '${{ matrix.os }}'
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '${{ matrix.go-version }}'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
